name: Run Web Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 8:00am Singapore Time (UTC+8)

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    env:
      GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
      GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      TO_EMAIL: ${{ secrets.TO_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run scraper
        run: python main.py